### ISSUE TITLE
How does it work? I get no completion hints/info.

### ISSUE THREAD

**Issue by pckujawa** [eladyarkoni/MySignaturePlugin#1]
Is there a particular hotkey or something? I tried Ctrl+Space and got an autocomplete box, but it doesn't have any info about the method. I'm using ST 2.0.1 build 2217 on 32-bit Win7.
Thanks!
Pat

**Comment by eladyarkoni** [comment]
Hi Pat!

Thank you for downloading my plugin MySign for sublime text editor.

This plugin works on save, It means that actually, when you save any file in your project, the plugin map all your javascript methods in any kind of form: var name = function() {} and name: function() {} and when the complete box is opened (ctrl+space or by the editor), It shows the methods in your project files with the signature.

I recommend you to read more in my post about this plugin: http://www.eladyarkoni.com/2012/09/sublime-text-auto-complete-plugin.html

Thank you again,

Elad.

**Comment by pckujawa** [comment]
Thanks for the clarification. I sent you a pull request which has some of that info added to the readme. However, I'm still not seeing an autocomplete list like the one in your blog post; I just see the default one.

**Comment by eladyarkoni** [comment]
Hi Pat,

I can't see your pull request. just the changes on your repository.
Please send me again and I'll approve it.

**Comment by eladyarkoni** [comment]
Ok. nevermind.
I reopened your pull request and merged it with my repo.
thanks for the changes!
