### ISSUE TITLE
return = self.get_autocomplete_list(prefix SyntaxError

### ISSUE THREAD

**Issue by arsham** [eladyarkoni/MySignaturePlugin#3]
Hi there,
I'm receiving this error on startup

Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./mysign.py", line 124
    return = self.get_autocomplete_list(prefix
           ^
SyntaxError: invalid syntax

**Comment by eladyarkoni** [comment]
Thank you!
my bad :)
fixed and commited.

you can re-install it.
